### ISSUE TITLE
Make a mod with just the gasoline engines

### ISSUE THREAD

**Issue by itsMaspi** [GangolfOvaert/IO-Overhaul#11]
Hey there!

I’m not sure if this mod is still being developed, but I’ll create this issue anyway.

I loved playing SE with Industrial Overhaul, but recently I decided to try a "vanilla" playthrough. However, I really miss the gasoline engines and would love to have them as a standalone mod.

I imagine it’s not too difficult, but I don’t have any experience with modding for SE, so I’m a bit lost with all the files. It would be great to still have OilSand and refine it to make gasoline (it could be simplified, perhaps directly from Crude Oil to Gasoline).

If you could help point me in the right direction, I would greatly appreciate it!

Also, if I end up making the mod and publishing it to the workshop, I would be more than happy to give you credit.

Thanks!

**Comment by itsMaspi** [comment]
Also, I'm not sure this is the right place to ask this, I don't know if this is a standalone mod or it has to be loaded with Industrial Overhaul and it reworks some of it's features...

**Comment by GangolfOvaert** [comment]
Development is stopped during summer, in winter it will continue.

Its not that hard. Hit me up on steam or tell me how i can contact you.

**Comment by itsMaspi** [comment]
You can contact me on discord if you like. My username is `itsmaspi`.

**Comment by itsMaspi** [comment]
I managed to get it working, if the owner of Industrial Overhaul gives me permission I'll post it on the workshop 😃
